import Heads from 'next/head'
import style from '../styles/layout.module.css'
import Menu from "./menu"

export default function layout({children,title}){
    return (
        <div>
            <Heads>
                <title>Store {title? `| ${title}`: ""} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Heads>

            
            <Menu />
            

            <div className={style.container}> {children} </div> 

        </div>
        
        
    );

    
}